version: "3.9"

services:
  db:
    image: "postgres"
    environment:
      POSTGRES_USER: adm
      POSTGRES_PASSWORD: adm
      POSTGRES_DB: form
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data/

volumes:
  dbdata: